server:
  port: 8080

spring:
  application:
    name: stock-quant-system
  
  datasource:
    url: jdbc:h2:mem:stockdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.quant: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Twitter监控配置
twitter:
  monitor:
    enabled: true
    target-user: xiaozhaolucky
    target-url: https://x.com/xiaozhaolucky
    check-interval: 30 # 秒
    timeout: 30 # 秒
    max-retries: 3 # 最大重试次数

# WebDriver配置
webdriver:
  headless: true # 无头模式
  user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
  timeout: 30 # 秒
  window-size: 1920,1080

# 股票数据配置
stock:
  data-source: futu-api  # futu-api 或 yahoo-finance
  update-interval: 60 # 秒

# 富途API配置
futu:
  api:
    enabled: true
    host: 127.0.0.1
    port: 11111
    enable-encrypt: false
    connection-timeout: 3000
    keep-alive-interval: 10
    user-agent: StockQuantSystem/1.0
    
    # 市场支持
    enable-us-stock: true
    enable-hk-stock: false
    enable-cn-stock: false
    
    # 数据订阅
    max-subscriptions: 100
    enable-realtime-quote: true
    enable-order-book: false
    enable-ticker: false

# StockPltr爬虫配置
stockpltr:
  crawl:
    enabled: true # 是否启用爬虫
    interval: 300 # 爬取间隔（秒）
    batch-size: 10 # 批量处理大小
    timeout: 30 # 请求超时时间（秒）
    max-retries: 3 # 最大重试次数
    delay-between-requests: 2000 # 请求间延迟（毫秒）
    
  data:
    retention-days: 30 # 数据保留天数
    enable-cache: true # 是否启用缓存
    cache-duration: 300 # 缓存持续时间（秒）
    
  website:
    base-url: https://www.stockpltr.com
    search-url: https://www.stockpltr.com/search
    stock-detail-url: https://www.stockpltr.com/stock
    
  monitoring:
    symbols: # 默认监控的股票代码
      - AAPL
      - TSLA
      - PLTR
      - NVDA
      - MSFT
      - GOOGL
      - AMZN
      - META
