server:
  port: 8080

spring:
  application:
    name: stock-quant-system
  
  datasource:
    url: jdbc:h2:mem:stockdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.quant: INFO
    org.springframework: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Twitter监控配置
twitter:
  monitor:
    enabled: true
    target-user: xiaozhaolucky
    check-interval: 30 # 秒

# 股票数据配置
stock:
  data-source: yahoo-finance
  update-interval: 60 # 秒
